apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secretproviderclass.yaml
- secretsynchronizer.yaml
- ./pvc
- ./external
- ./services
- ./ingress
#Excluding init here as we have separate workflows to deploy those
#- ./init
