# This is a SecretProviderClass using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sitecore-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: sitecore-database
      type: Opaque
      data:
        - objectName: sitecore-databaseservername
          key: sitecore-databaseservername.txt
        - objectName: sitecore-databaseusername
          key: sitecore-databaseusername.txt
        - objectName: sitecore-databasepassword
          key: sitecore-databasepassword.txt
        - objectName: sitecore-core-database-username
          key: sitecore-core-database-username.txt
        - objectName: sitecore-core-database-password
          key: sitecore-core-database-password.txt
        - objectName: sitecore-web-database-username
          key: sitecore-web-database-username.txt
        - objectName: sitecore-web-database-password
          key: sitecore-web-database-password.txt
        - objectName: sitecore-forms-database-username
          key: sitecore-forms-database-username.txt
        - objectName: sitecore-forms-database-password
          key: sitecore-forms-database-password.txt
        - objectName: sitecore-exm-master-database-username
          key: sitecore-exm-master-database-username.txt
        - objectName: sitecore-exm-master-database-password
          key: sitecore-exm-master-database-password.txt
        - objectName: sitecore-messaging-database-username
          key: sitecore-messaging-database-username.txt
        - objectName: sitecore-messaging-database-password
          key: sitecore-messaging-database-password.txt
        - objectName: sitecore-marketing-automation-database-username
          key: sitecore-marketing-automation-database-username.txt
        - objectName: sitecore-marketing-automation-database-password
          key: sitecore-marketing-automation-database-password.txt
        - objectName: sitecore-reference-data-database-username
          key: sitecore-reference-data-database-username.txt
        - objectName: sitecore-reference-data-database-password
          key: sitecore-reference-data-database-password.txt
        - objectName: sitecore-collection-shardmapmanager-database-username
          key: sitecore-collection-shardmapmanager-database-username.txt
        - objectName: sitecore-collection-shardmapmanager-database-password
          key: sitecore-collection-shardmapmanager-database-password.txt
        - objectName: sitecore-processing-pools-database-username
          key: sitecore-processing-pools-database-username.txt
        - objectName: sitecore-processing-pools-database-password
          key: sitecore-processing-pools-database-password.txt
        - objectName: sitecore-master-database-username
          key: sitecore-master-database-username.txt
        - objectName: sitecore-master-database-password
          key: sitecore-master-database-password.txt
        - objectName: sitecore-reporting-database-username
          key: sitecore-reporting-database-username.txt
        - objectName: sitecore-reporting-database-password
          key: sitecore-reporting-database-password.txt
        - objectName: sitecore-processing-tasks-database-username
          key: sitecore-processing-tasks-database-username.txt
        - objectName: sitecore-processing-tasks-database-password
          key: sitecore-processing-tasks-database-password.txt
        - objectName: sitecore-processing-engine-storage-database-username
          key: sitecore-processing-engine-storage-database-username.txt
        - objectName: sitecore-processing-engine-storage-database-password
          key: sitecore-processing-engine-storage-database-password.txt
        - objectName: sitecore-processing-engine-tasks-database-username
          key: sitecore-processing-engine-tasks-database-username.txt
        - objectName: sitecore-processing-engine-tasks-database-password
          key: sitecore-processing-engine-tasks-database-password.txt
        - objectName: sitecore-database-elastic-pool-name
          key: sitecore-database-elastic-pool-name.txt
    - secretName: sitecore-admin
      type: Opaque
      data:
        - objectName: sitecore-adminpassword
          key: sitecore-adminpassword.txt
    - secretName: sitecore-identity
      type: Opaque
      data:
        - objectName: sitecore-identitysecret
          key: sitecore-identitysecret.txt
    - secretName: sitecore-identitycertificate
      type: Opaque
      data:
        - objectName: sitecore-identitycertificate
          key: sitecore-identitycertificate.txt
        - objectName: sitecore-identitycertificatepassword
          key: sitecore-identitycertificatepassword.txt
    - secretName: sitecore-telerik
      type: Opaque
      data:
        - objectName: sitecore-telerikencryptionkey
          key: sitecore-telerikencryptionkey.txt
    - secretName: sitecore-reporting
      type: Opaque
      data:
        - objectName: sitecore-reportingapikey
          key: sitecore-reportingapikey.txt
    - secretName: sitecore-solr
      type: Opaque
      data:
        - objectName: sitecore-solr-connection-string
          key: sitecore-solr-connection-string.txt
        - objectName: sitecore-solr-core-prefix-name
          key: sitecore-solr-core-prefix-name.txt
    - secretName: sitecore-protect-media-requests
      type: Opaque
      data:
        - objectName: sitecore-media-request-protection-shared-secret
          key: sitecore-media-request-protection-shared-secret.txt
    - secretName: sitecore-solr-xdb
      type: Opaque
      data:
        - objectName: sitecore-solr-connection-string-xdb
          key: sitecore-solr-connection-string-xdb.txt
    - secretName: sitecore-rendering
      type: Opaque
      data:
        - objectName: sitecore-jss-editing-secret
          key: sitecore-jss-editing-secret.txt
        - objectName: sitecore-jss-api-key
          key: sitecore-jss-api-key.txt
  parameters:
    objects: |
      array:
        - |
          objectName: sitecore-adminpassword
          objectType: secret
        - |
          objectName: sitecore-databaseservername
          objectType: secret
        - |
          objectName: sitecore-databaseusername
          objectType: secret
        - |
          objectName: sitecore-databasepassword
          objectType: secret
        - |
          objectName: sitecore-core-database-username
          objectType: secret
        - |
          objectName: sitecore-core-database-password
          objectType: secret
        - |
          objectName: sitecore-web-database-username
          objectType: secret
        - |
          objectName: sitecore-web-database-password
          objectType: secret
        - |
          objectName: sitecore-forms-database-username
          objectType: secret
        - |
          objectName: sitecore-forms-database-password
          objectType: secret
        - |
          objectName: sitecore-exm-master-database-username
          objectType: secret
        - |
          objectName: sitecore-exm-master-database-password
          objectType: secret
        - |
          objectName: sitecore-messaging-database-username
          objectType: secret
        - |
          objectName: sitecore-messaging-database-password
          objectType: secret
        - |
          objectName: sitecore-solr-connection-string
          objectType: secret
        - |
          objectName: sitecore-solr-core-prefix-name
          objectType: secret
        - |
          objectName: sitecore-media-request-protection-shared-secret
          objectType: secret
        - |
          objectName: sitecore-marketing-automation-database-username
          objectType: secret
        - |
          objectName: sitecore-marketing-automation-database-password
          objectType: secret
        - |
          objectName: sitecore-reference-data-database-username
          objectType: secret
        - |
          objectName: sitecore-reference-data-database-password
          objectType: secret
        - |
          objectName: sitecore-collection-shardmapmanager-database-username
          objectType: secret
        - |
          objectName: sitecore-collection-shardmapmanager-database-password
          objectType: secret
        - |
          objectName: sitecore-processing-pools-database-username
          objectType: secret
        - |
          objectName: sitecore-processing-pools-database-password
          objectType: secret
        - |
          objectName: sitecore-solr-connection-string-xdb
          objectType: secret
        - |
          objectName: sitecore-master-database-username
          objectType: secret
        - |
          objectName: sitecore-master-database-password
          objectType: secret
        - |
          objectName: sitecore-reporting-database-username
          objectType: secret
        - |
          objectName: sitecore-reporting-database-password
          objectType: secret
        - |
          objectName: sitecore-identitysecret
          objectType: secret
        - |
          objectName: sitecore-telerikencryptionkey
          objectType: secret
        - |
          objectName: sitecore-reportingapikey
          objectType: secret
        - |
          objectName: sitecore-identitycertificate
          objectType: secret
        - |
          objectName: sitecore-identitycertificatepassword
          objectType: secret
        - |
          objectName: sitecore-processing-tasks-database-username
          objectType: secret
        - |
          objectName: sitecore-processing-tasks-database-password
          objectType: secret
        - |
          objectName: sitecore-processing-engine-storage-database-username
          objectType: secret
        - |
          objectName: sitecore-processing-engine-storage-database-password
          objectType: secret
        - |
          objectName: sitecore-processing-engine-tasks-database-username
          objectType: secret
        - |
          objectName: sitecore-processing-engine-tasks-database-password
          objectType: secret
        - |
          objectName: sitecore-jss-editing-secret
          objectType: secret
        - |
          objectName: sitecore-jss-api-key
          objectType: secret
        - |
          objectName: sitecore-database-elastic-pool-name
          objectType: secret
