---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-synchronizer
spec:
  selector:
    matchLabels:
      app: secrets-synchronizer
  template:
    metadata:
      labels:
        app: secrets-synchronizer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: secrets-synchronizer
          image: "docker.io/library/alpine:3.12.1"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          command: [ "sleep" ]
          args: [ "infinity" ]
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "20Mi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: sitecore-secrets