apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sitecore-cd
        resources:
          requests:
            memory: 1Gi
            cpu: 1000m
          limits:
            memory: 3Gi
            cpu: 2000m