apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sitecore-cm
        resources:
          requests:
            memory: 800Mi
            cpu: 1000m
          limits:
            memory: 3Gi
            cpu: 2000m