apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: sitecore-mssql
  newName: scr.sitecore.com/sxp/sitecore-xm1-mssql
  newTag: 10.3-ltsc2019
- name: sitecore-redis
  newName: redis
  newTag: 4.0.14-alpine
- name: sitecore-solr
  newName: solr
  newTag: 8.11.2
resources:
- mssql.yaml
- redis.yaml
- solr.yaml